apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "teste"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "teste"
    spec:
      containers:
        - name: "teste"
          image: "groceryshop.azurecr.io/teste"
          ports:
          - containerPort: 80